### PR TITLE
Allow disabling of automatic widget re-binding 

### PR DESCRIPTION
**Pull request by ericfreese**
Addresses github #411

### CODE REVIEW

**Comment by romkatv** [comment]
Most plugins rebind widgets only during sourcing. To ensure that zsh-autosuggestions rebinds widgets after everyone else, you could hook `precmd`, run `_zsh_autosuggest_start` from it, and then unhook `precmd` if `ZSH_AUTOSUGGEST_MANUAL_REBIND` is set. This would be more robust than the current code because it will work regardless of the order in which different plugins are sources. The only case where `ZSH_AUTOSUGGEST_MANUAL_REBIND` wouldn't work (compared to the current code that rebinds everything on every `precmd`) is when widgets are defined or rebound after the first prompt is rendered. This limitation is reasonable and easy to understand.

**Comment by ericfreese** [comment]
> you could hook precmd, run _zsh_autosuggest_start from it, and then unhook precmd if ZSH_AUTOSUGGEST_MANUAL_REBIND is set

Cool, this is essentially what the PR does :smile:

**Comment by romkatv** [comment]
> Cool, this is essentially what the PR does

:man_facepalming:

LGTM!

**Comment by leotaku** [comment]
Great, Thank you! This seems like it's the best option for most users. Although I will probably still remove the `precmd` hook and run `_zsh_autosuggest_start` in my configuration, just to avoid the flicker produced by the first `precmd`.

**Pull request merged**
