### PR TITLE
play well with zsh-syntax-highlight

### PR DESCRIPTION
**Pull request by seletskiy**

### CODE REVIEW

**Comment by ericfreese** [comment]
Is this meant to address #126?

**Comment by seletskiy** [comment]
@ericfreese: Yes, it is. Sorry, I didn't look for existing issues. Just fixed by myself.

**Comment by seletskiy** [comment]
@ericfreese: ping?

**Comment by ericfreese** [comment]
@seletskiy Sorry, i've been busy with work. Will get to this as time allows.

**Comment by molovo** [comment]
Just had a play with this (I was trying to resolve the same issue on the syntax-highlighting side). Seems to resolve the issue, I no longer get a segfault when re-sourcing my .zshrc in the active session.

**Comment by josefson** [comment]
It didn't work for my system. Using zsh 5.2 (x86_64-apple-darwin14.5.0) and latest version of both plugins.

**Comment by devnall** [comment]
Worked for me on zsh 5.2 (x86_64-apple-darwin14.5.0) 

@danielshahaf 's patch in Issue 126 also worked.

**Comment by NikkyAI** [comment]
fixes the issue for me, tested on cygwin64 loading with zplug
will test on arch later and update this

hope this will be merged

**Comment by ericfreese** [comment]
Thank you for this. I've implemented something very similar on the `develop` branch, which should solve the problems with `z-sy-h` plugin. Please let me know if it doesn't.

**Comment by NikkyAI** [comment]
with `zplug "zsh-users/zsh-autosuggestions", at:develop``
and forcing a update the issue of zsh crashing after sourcing this plugin a second or third time was fixed for me

**Pull request closed without merging**
