### PR TITLE
Fix vi partial accept

### PR DESCRIPTION
**Pull request by toadjaune**
Cf https://github.com/zsh-users/zsh-autosuggestions/issues/188

### CODE REVIEW

**Comment by z0rc** [comment]
Please use double square brackets (`[[ ]]`) for code consistency.

**Comment by ericfreese** [comment]
Thanks for fixing this! Can you add a test?

**Comment by toadjaune** [comment]
Code style fixed, I'll look into making a test.

**Comment by toadjaune** [comment]
@ericfreese, I can't get the already existing tests to pass : 
`
rspec ./spec/integrations/wrapped_widget_spec.rb:15 # a wrapped widget initialized before sourcing the plugin executes the custom behavior and the built-in behavior
rspec ./spec/integrations/wrapped_widget_spec.rb:32 # a wrapped widget initialized after sourcing the plugin executes the custom behavior and the built-in behavior
`
This happens both on this branch, on develop, and on master.

Is this a known issue ? Is something wrong in my test environment ? Should I just ignore these errors and go ahead adding a test ?

**Comment by toadjaune** [comment]
Here is a test, I don't know if it seems clean enough, though.

**Comment by ericfreese** [comment]
Thanks @toadjaune! I will take a look at this soon.

**Comment by ericfreese** [comment]
I've added [an additional test](https://github.com/zsh-users/zsh-autosuggestions/blob/5ac9363f54b658f234950434f03c540092836f7a/spec/integrations/vi_mode_spec.rb#L23-L36) to the new `fixes/vi-partial-accept` branch that tests a behavior that seems intuitive to me: not accepting the first character of the next word when using `vi-forward-word` to partially accept a suggestion.

With the proposed patch, the new test fails with:

```
  expected: "foobar baz"
       got: "foobar fbaz"
```

What do you think about this case? What do you think would be the most intuitive behavior?

I'm not sure the most elegant way to include the char under the cursor for `vi-forward-word-end`, but not include it for `vi-forward-word`. Ideally both of these tests will pass.

**Comment by ericfreese** [comment]
The more I think about this, the more I think it would be ok for `vi-forward-word` to accept the first char of the next word. You could still accept to just before it by using `f<space>` (which makes me realize I need to add `vi-find-next-char` and `vi-find-next-char-skip` to `ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS`

**Comment by IngoHeimbach** [comment]
In my opinion, the vi widgets should move the cursor like they usually do, so it should be ok to accept the first character of a new word if necessary. In that case, the user can still press `C` do delete this one character and change to insert mode.

**Comment by ericfreese** [comment]
Ok I've applied a similar patch with https://github.com/zsh-users/zsh-autosuggestions/commit/393f7b8bb9d83aef1847d39ad20c6a73849917b8 that should fix issue #188. It's been merged to `develop` branch and will be included in the next release.

Thanks @IngoHeimbach and @toadjaune for your effort on this!

**Comment by IngoHeimbach** [comment]
Thanks everyone for your work! :+1:

**Comment by toadjaune** [comment]
I think that we should probably simply let widgets such as `vi-forward-word` do their job normally, and don't try to change their behavior in any way.

It would be a surprising (and pretty terrible) experience to have the cursor behaving differently depending on whether we're moving through the beginning of the command or through the suggestion. Same goes about behaving differently with and without zsh-autosuggestions.

Therefore, since in `vicmd` keymap, the cursor can never be after the last character, and since `vi-forward-word` will usually bring it on the first letter of a word, I agree that the sanest thing to do here would be … nothing specific (ie let it accept the first letter)

**Comment by toadjaune** [comment]
Oh, I had not reloaded my tab, missed the two latest messages, sorry ^^'

Your solution is probably more elegant than mine, I tried to make something similar but couldn't get it to work.

However, I'm a bit worried that we might encounter issues down the road, by not using $LBUFFER and $RBUFFER, in some weird edge case.

Anyway, thanks everyone, that's a good needle out of our foot :)

**Pull request closed without merging**
