### PR TITLE
Features/completion suggestions

### PR DESCRIPTION
**Pull request by ericfreese**
- Adds new `completion` strategy (#111).
- Renames `default` strategy to `history`.
- Makes `ZSH_AUTOSUGGEST_STRATEGY` an array. Strategies will be tried successively and first suggestion found will be used.

`completion` strategy can be pretty slow, so consider turning on `ZSH_AUTOSUGGEST_USE_ASYNC`.

### To Do

- [x] Write a test for it
- [x] Figure out why [CI](https://circleci.com/gh/zsh-users/zsh-autosuggestions/tree/features%2Fcompletion-suggestions) is failing
- [x] Is it possible to suggest non-exported variables? They're not available in the pty.
- [x] Write test for and fix issue with carriage returns in async mode (ex: `echo '^M'` in buffer)
- [x] Fix on older versions of zsh
- [x] Support `ZSH_AUTOSUGGEST_STRATEGY` as an array of strategies to try successively.
- [x] Fix blowing up when single quote entered in buffer.
- [ ] ~Look into (and fix?) leaking pty processes on Mac OSX~ not sure about this one... will wait for confirmed bug reports since it's experimental anyhow.

### CODE REVIEW

**Comment by megalithic** [comment]
would LOVE this to be merged.

**Comment by alok** [comment]
I seem to have an issue with this. If I type something like `e` (alias for `$EDITOR`), then suddenly I stop getting completions. It seems to happen if I type in a short command and look for a completion, and lasts for the entire terminal session.

**Comment by ericfreese** [comment]
@alok Interesting, I get more suggestions after aliasing `e` (it suggests `egrep`).

Can you reproduce using `zsh -f` and sourcing the plugin manually? If not, can you find the offending settings in your `.zshrc`?

**Comment by alok** [comment]
Appears to have magically fixed itself.

**Comment by ericfreese** [comment]
Yeah I've run into that. It's on the todo list as "Fix blowing up when single quote entered in buffer."

**Comment by alok** [comment]
FWIW I get leaking processes on the latest release of macOS High Sierra. Not sure how to replicate though.

**Comment by ericfreese** [comment]
Dang I was hoping it was something unrelated on my mac. I'll make an issue to track it. I seem to not have the problem on my linux machine for some reason.

**Pull request merged**
